AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CFNDefaultDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: movie-rec-db
        Description: Default DB to store data