AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3BucketName:
    Type: String 
    Description: S3 bucket where all data, code is going to be stored
    Default: "movie-recommendation-s3"
  SageMakerDomainName:
    Type: String
    Description: SageMaker domain name
    Default: "movie-recommendation-sys"
  GitHubRepo:
    Type: String
    Description: URL of the GitHub repository to clone
    Default: "https://github.com/ArvindReddyBobbili/ReviewRadar"
  VpcStackName:
    Type: String
    Description: Name of the VPC stack
    Default: "MovieRecommendationVPC"
  VpcRegion:
    Type: String
    Description: AWS Region for VPC creation
    Default: "us-east-1"
  ImageId:
    Type: String
    Description: Amazon Linux 2023 AMI for the correct region
    Default: "ami-0230bd60aa48260c6"
  KeyName:
    Type: String
    Description: SSH Key Name for troubleshooting purpose
    Default: "review-radar"

Resources:
  CodeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc-stack.yaml
      Parameters:
        VpcName: MyVPC
        VpcRegion: !Ref VpcRegion
        VpcStackName: !Ref VpcStackName

  InstanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: instance-stack.yaml
      Parameters:
        S3BucketName: !Ref S3BucketName
        GitHubRepo: !Ref GitHubRepo
        SubnetId: !GetAtt VPCStack.Outputs.SubnetId
        SecurityGroupId: !GetAtt VPCStack.Outputs.SecurityGroupId
        KeyName: !Ref KeyName
        ImageId: !Ref ImageId

  SageMakerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InstanceStack
    Properties:
      TemplateURL: sagemaker-stack.yaml
      Parameters:
        S3BucketName: !Ref S3BucketName
        SageMakerDomainName: !Ref SageMakerDomainName
        GitHubRepo: !Ref GitHubRepo
        SubnetId: !GetAtt VPCStack.Outputs.SubnetId
        VpcId: !GetAtt VPCStack.Outputs.VpcId
  
  CustomStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SageMakerStack
    Properties:
      TemplateURL: custom-stack.yaml
      Parameters:
        S3BucketName: !Ref S3BucketName
        SageMakerDomainName: !Ref SageMakerDomainName
        GitHubRepo: !Ref GitHubRepo
        SubnetId: !GetAtt VPCStack.Outputs.SubnetId
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  GlueStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CustomStack
    Properties:
      TemplateURL: glue-stack.yaml


Outputs:
  S3BucketNameOutput:
    Value: !Ref S3BucketName
    Description: Name of the created S3 bucket
  SageMakerUserProfileRoleOutput:
    Value: !GetAtt SageMakerStack.Outputs.SageMakerUserProfileRoleOutput
    Description: ARN of the IAM role associated with the SageMaker User Profile
  SageMakerDomainJupyterURLOutput:
    Value: !GetAtt SageMakerStack.Outputs.SageMakerDomainJupyterURLOutput
    Description: URL of the SageMaker Studio for accessing Jupyter notebooks